### ISSUE TITLE
Soundcloud links in playlist do not auto-play for users

### ISSUE THREAD

**Issue by CuckooRules** [calzoneman/sync#758] opened 2018-07-12 21:11 UTC
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  - [x] Using a clean channel with no customizations
  
### Description of the Problem ###

  - Add Soundcloud link in playlist
  - The track seems to auto-play, however each user has to click the play button in order to 'start' it, which then begins at wherever the song has progressed.  Song appears to be auto-playing in background but all users have to click play button to begin audio. 
  - Audio should auto-play for all users without having to click play button. 

### System Information ###

  Happens on Windows using Chrome.  User reported same experience using Linux with chrome.  
  - **Error Messages Displayed:**
     N/A
  - **Screenshot of JavaScript Console:**
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._
![jconsole](https://user-images.githubusercontent.com/18434734/42659464-f7f27916-85ed-11e8-92e6-e6b5e5880d0e.png)

**Comment by calzoneman** [comment] 2018-07-15 17:37
This appears to be a Chromium-specific regression; I can confirm that autoplay works fine on Firefox, but on Chromium I get errors like:

```
Uncaught (in promise) DOMException: The user aborted a request.
```

...every time CyTube tries to sync the player, and the song doesn't play.

Interestingly, the player does load and display the pause icon (indicating that it is trying to autoplay) for a split second before it appears to transition to some kind of "related songs" overlay.

**Comment by calzoneman** [comment] 2018-07-15 18:32
~~It appears that Soundcloud is firing the `READY` event before it is actually ready (if you call `play()` after receiving `READY`, it breaks the player state on Chromium).  If it were any other media provider I'd file a bug with them, but past experience shows it takes approximately 4 years for Soundcloud to take action on any bug I report, so we'll just have to settle for a workaround.~~

**Comment by calzoneman** [comment] 2018-07-15 19:18
I'm probably not going to look into this any more today, but I have some suspicions.  The API calls seem to work fine from the browser console, but not when running in CyTube's JavaScript.  Additionally, Soundcloud's own `auto_play` parameter isn't working.

Based on looking at the obfuscated code, it looks like Soundcloud switched to some DASH-style playback where they asynchronously buffer the audio and play it back through a browser API rather than just embedding an MP3 directly.  Given the symptoms, I'm guessing Chromium doesn't allow this API to be used programmatically unless the user takes some action to initiate it (presumably to protect users from shitty websites with autoplaying ads, but at the expense of breaking websites like CyTube where autoplaying is the intended effect).  Haven't had time to research this.

Other browsers may not be hitting this code path because the obfuscated JavaScript includes an extensive `isSupported()` function that checks for various browser globals and whether the browser is Firefox (lol).

**Comment by calzoneman** [comment] 2018-07-15 19:29
Well, looks like my suspicions were correct: if I toggle the autoplay flag described on https://developers.google.com/web/updates/2017/09/autoplay-policy-changes to "No user gesture is required", then autoplay works as expected in Chromium.

This unfortunately means that it's a Chrome "feature" and not something Soundcloud or I are likely to be able to fix, because Chrome is doing it on purpose.  However, according to that documentation, presumably you could individually "train" Chrome to realize that you want Soundcloud widgets to autoplay.

**Comment by calzoneman** [comment] 2018-07-17 00:42
Closing as wontfix (although it's really more of a "can't fix")

**Closed as completed by calzoneman** 2018-07-17 00:42 UTC
Labels: Google's fault, 3rd-party issue
