### ISSUE TITLE
Private or deleted Vimeo videos in queue lock channel

### ISSUE THREAD

**Issue by golden-curry** [calzoneman/sync#906] opened 2021-03-25 20:07 UTC
If a live Vimeo link is added to a playlist, but changed to be private or is deleted before the video comes on, causes Cytube channels to be unable to advance in the playlist, even when the leader attempts to force another video to play. So far, the only fix is removing everyone from the channel and joining again. 
You can reproduce this bug by uploading a video to Vimeo, keeping it public at first, then adding a different video first, then the test Vimeo video, then another video to the playlist. Play the first video and then make the Vimeo video private. Once the first video is done, the Vimeo video will try to load. You should not be able to advance to the next video in the playlist. Once all users have left the channel, the next video in the playlist will load once a user joins the channel again.

**Comment by calzoneman** [comment] 2021-03-27 04:08
Do you have an example video that demonstrates the problem?  I'm not able to break the player in the way you described.

Are you encountering this behavior on cytu.be or on your own/a third party hosted site?

**Comment by calzoneman** [comment] 2021-04-24 21:51
Closing since requester has not provided reproducible example.

**Closed as completed by calzoneman** 2021-04-24 21:51 UTC
