### ISSUE TITLE
Google Drive videos working improperly after update

### ISSUE THREAD

**Issue by BigEBankston** [calzoneman/sync#615] opened 2016-08-11 15:36 UTC
- What triggers the problem?
  Adding a google drive video into the playlist then playing it.
- What happens?
  Video is stretched out and is cut out by the edge of the window (http://puu.sh/qxDCj/218fbcc2ec.png)
  Video buttons are also gone.
- What do you expect to happen instead?
  The video to be resized properly to the window with the video buttons back again, this was working untill the latest update which added "CyTube now supports embedding videos from streamable.com as well as HLS livestreams."

**Comment by JorgenPhi** [comment] 2016-08-11 16:05
This is not caused by a CyTube update. I am using 6e416fe and I have this issue as well.

**Comment by calzoneman** [comment] 2016-08-12 04:12
Yes, this is unrelated to the recent update.  It appears Google swapped out the SWF for a different one that behaves weirdly.  I was unable to make any progress after wrestling with it for a while, so I have a [hacky potential solution](https://github.com/calzoneman/sync/tree/gd-html5-hack) that is being tested on http://beta.synchtube.me and will later be deployed to cytu.be.

**Comment by LukteDukte** [comment] 2016-08-12 15:04
It seems that the new video player is causing problem with a few users. Some, including me, can't see the video and showing a message saying "The media could not be loaded, either because the server or network failed or because the format is not supported".

The solution that some users found is using an VPN, [link](https://chrome.google.com/webstore/detail/betternet-free-vpn/gjknjjomckknofjidppipffbpoekiipm), making the video view-able for 5 minutes then stops working.

**Comment by calzoneman** [comment] 2016-08-12 15:41
Can you please provide a screenshot of the JavaScript console when the error occurs?  Press F12 and select the "Console" tab.

In the meantime, I added a quickfix user option to opt-in to using the old broken player.

**Comment by JorgenPhi** [comment] 2016-08-12 15:45
I dont have a screenshot right now, but essentially every video file
request that is attempted fails with a 403. Sometimes going into incognito
mode will fix it, other times it will work normally and fail in incognito
mode. Very bizzare.

While I was testing the new player I had native ipv6 if that matters.

**Comment by LukteDukte** [comment] 2016-08-12 15:55
Here is a picture you requested @calzoneman 

![video error](https://cloud.githubusercontent.com/assets/20993132/17628518/e6fbea02-60b5-11e6-8f14-74a16c81d0b7.png)

**Comment by darkchiefy** [comment] 2016-08-13 00:54
This has since been put up by the admins 

"Update
A different Google Drive player is now used to work around the issues from earlier. Please clear your cache and refresh if you continue to have issues. Thank you for your patience.
If the new player does not work for you, you can go to Options->Playback and check "Use Old Broken Drive Player". This will allow you to continue to use the old player which is off center and has no controls. You must refresh to see this option, and click the "refresh video" button after toggling it for the change to take effect."

However, i am still having problems with the new player. i have been using safari and google chrome and i cleared the cached on both but the new player for google drive videos still isn't working (at least, not on cytube). i can see videos with the broken system but that has the stretched out, off centre, cut off video. Any help you could provide me would be greatly appreciated

**Comment by ghost** [comment] 2016-08-13 01:48
I have noticed that the video url's now have an ip address in the url for the video file. it looks like each ip address needs to generate its own unique url now. the url that was generated has the servers ip.

**Comment by calzoneman** [comment] 2016-08-13 01:50
Please refrain from speculation on this thread.

@darkchiefy Now that I am home, I am investigating the issues people are having with the new player.  In the mean time, you can use the old player.  I know it is not the best experience, but this is out of my control as it was updated/broken by Google without warning.

**Comment by darkchiefy** [comment] 2016-08-13 18:23
it seems my friends who live in the USA don't really have this issue but those outside of the USA like me do have the issue

**Comment by calzoneman** [comment] 2016-08-15 03:33
Google may have some region restrictions in place in addition to the IP restriction that this workaround was intended to bypass.

**Comment by calzoneman** [comment] 2016-08-15 04:19
I'm probably just going to drop native support for google drive and require a userscript to be able to play it.  It would solve a lot of problems.

**Comment by darkchiefy** [comment] 2016-08-16 22:15
whatever is working on cytube beta is working for me

**Comment by calzoneman** [comment] 2016-08-17 01:46
It's the same code.  For technical reasons, the same link when provided by different servers can have different results for the same user.  I'm proceeding with replacing the native video player by a userscript to alleviate the fragility and complexity.

**Comment by Jan02** [comment] 2016-08-19 04:25
the new userscript isn't making a difference.

> Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }video.js:8:17750
> 
> Caught error, trying next sourceplayer.js:1:8541
> 
> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }video.js:8:17750
> 
> Caught error, trying next sourceplayer.js:1:8541
> 
> HTTP load failed with status 403. Load of media resource https://r5---sn-nx57ynel.c.docs.google.com/videoplayback?requiressl=yes&id=cc7ede2a4cff125e&itag=59&source=webdrive&ttl=transient&app=texmex&ip=23.226.225.183&ipbits=8&expire=1471592808&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire&signature=3F21D2960290A78D623C5826A5CA8B0DA75A2B1D.8DF6E4773892A610F639494C90AB75EC57919013&key=ck2&mm=30&mn=sn-nx57ynel&ms=nxu&mt=1471578332&mv=u&nh=IgpwcjAyLnNlYTAzKgkxMjcuMC4wLjE&pl=24&sc=yes failed.NetworkRequestListener.js:17:8
> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }video.js:8:17750
> 
> Caught error, trying next sourceplayer.js:1:8541
> 
> HTTP load failed with status 403. Load of media resource https://r5---sn-nx57ynel.c.docs.google.com/videoplayback?requiressl=yes&id=cc7ede2a4cff125e&itag=18&source=webdrive&ttl=transient&app=texmex&ip=2604:180:1::43f5:93e&ipbits=32&expire=1471592808&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire&signature=4574AD783A604CBF91BAF3497A100AB424354A0B.B7644B430F948FBE40A2C1E223214927B149741A&key=ck2&mm=30&mn=sn-nx57ynel&ms=nxu&mt=1471578135&mv=m&nh=IgpwcjAyLnNlYTAzKgkxMjcuMC4wLjE&pl=49&sc=yes failed.NetworkRequestListener.js:17:8
> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }video.js:8:17750
> 
> Caught error, trying next sourceplayer.js:1:8541
> 
> HTTP load failed with status 403. Load of media resource https://r5---sn-nx57ynel.c.docs.google.com/videoplayback?requiressl=yes&id=cc7ede2a4cff125e&itag=43&source=webdrive&ttl=transient&app=texmex&ip=2604:180:1::43f5:93e&ipbits=32&expire=1471592808&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire&signature=B1E9C8B091049A33A17E5D8C84F44892DD62E9FD.7FAB900D3E1D14071EB443A6A1022B9F928D0956&key=ck2&mm=30&mn=sn-nx57ynel&ms=nxu&mt=1471578135&mv=m&nh=IgpwcjAyLnNlYTAzKgkxMjcuMC4wLjE&pl=49&sc=yes failed.NetworkRequestListener.js:17:8
> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }video.js:8:17750
> 
> Caught error, trying next sourceplayer.js:1:8541
> 
> HTTP load failed with status 403. Load of media resource https://r5---sn-nx57ynel.c.docs.google.com/videoplayback?requiressl=yes&id=cc7ede2a4cff125e&itag=18&source=webdrive&ttl=transient&app=texmex&ip=23.226.225.183&ipbits=8&expire=1471592808&sparams=requiressl%2Cid%2Citag%2Csource%2Cttl%2Cip%2Cipbits%2Cexpire&signature=147AAC8F8254BACBE2A0D2BCB9E765FBC68536CC.22DA74569113044E55FECD6009E6883F1C6AD0C7&key=ck2&mm=30&mn=sn-nx57ynel&ms=nxu&mt=1471578332&mv=u&nh=IgpwcjAyLnNlYTAzKgkxMjcuMC4wLjE&pl=24&sc=yes failed.NetworkRequestListener.js:17:8

**Comment by calzoneman** [comment] 2016-08-19 04:32
1. Can you confirm you are using https://cytu.be?  Other sites will have to generate a different userscript, I haven't written the documentation for this yet.
2. Can you open the JS console (press F12 and select the "Console" tab) and type in `window.hasDriveUserscript` and check the result?
3. Assuming the answer to (1) is yes and the answer to (2) is `true`, that means the userscript should be running, so you can try running `localStorage.setItem('cytube_drive_debug', true)`, then refreshing the page, then taking a screenshot of the JS console once the video has loaded (or errored out).

**Comment by Jan02** [comment] 2016-08-19 04:40
in options do I have to use old style or new  style player?
1. http://cutu.be
2. 

> content script runtime.onMessage:  tabupdatecontent_script.js:91:2
> content script runtime.onMessage:  update_shortcutscontent_script.js:91:2
> content script runtime.onMessage:  tabupdatecontent_script.js:91:2
> Connecting to {"url":"https://cytu.be:10443","secure":true}callbacks.js:1:409
> content script runtime.onMessage:  tabupdatecontent_script.js:91:2
> window.hasDriveUserscript
> undefined

3-

> localStorage.setItem('cytube_drive_debug', true)
> undefined

**Comment by calzoneman** [comment] 2016-08-19 04:41
If `hasDriveUserscript` is `undefined`, that means the userscript is not running.  Which browser and userscript plugin are you using?

**Comment by Jan02** [comment] 2016-08-19 04:43
can confirm the script works with chrome but not firefox

**Comment by calzoneman** [comment] 2016-08-19 04:44
Which userscript manager are you using for Firefox?  Tampermonkey?  Greasemonkey?  Scriptish?

**Comment by Jan02** [comment] 2016-08-19 04:45
## Application Basics

Name: Firefox
Version: 48.0
Build ID: 20160726073904
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
OS: Windows_NT 10.0 x86-64
Multiprocess Windows: 0/1 (Disabled)
Safe Mode: false

## Crash Reports for the Last 3 Days

Report ID: bp-f711919e-e680-4c73-bd85-d64b32160817
Submitted: 1 day ago

All Crash Reports

## Extensions

Name: Firefox Hello Beta
Version: 1.4.4
Enabled: true
ID: loop@mozilla.org

Name: Greasemonkey
Version: 3.8
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Multi-process staged rollout
Version: 1.1
Enabled: true
ID: e10srollout@mozilla.org

Name: Pocket
Version: 1.0.4
Enabled: true
ID: firefox@getpocket.com

Name: Free Download Manager extension
Version: 2.1.12
Enabled: false
ID: fdm_ffext@freedownloadmanager.org

## Graphics

Features
Compositing: Direct3D 11
Asynchronous Pan/Zoom: none
WebGL Renderer: Google Inc. -- ANGLE (NVIDIA GeForce GTX 460 Direct3D11 vs_5_0 ps_5_0)
Hardware H264 Decoding: Yes; Using D3D11 API
Direct2D: true
DirectWrite: true (10.0.10586.494)
GPU #1
Active: Yes
Description: NVIDIA GeForce GTX 460
Vendor ID: 0x10de
Device ID: 0x0e22
Driver Version: 10.18.13.6839
Driver Date: 6-2-2016
Drivers: nvd3dumx,nvwgf2umx,nvwgf2umx,nvwgf2umx nvd3dum,nvwgf2um,nvwgf2um,nvwgf2um
Subsys ID: 00000000
RAM: 1024

Diagnostics
AzureCanvasAccelerated: 0
AzureCanvasBackend: direct2d 1.1
AzureContentBackend: direct2d 1.1
AzureFallbackCanvasBackend: cairo

## Important Modified Preferences

browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 1
browser.download.importedFromSqlite: true
browser.places.smartBookmarksVersion: 8
browser.sessionstore.upgradeBackup.latestBuildID: 20160726073904
browser.startup.homepage_override.buildID: 20160726073904
browser.startup.homepage_override.mstone: 48.0
dom.apps.reset-permissions: true
extensions.lastAppVersion: 48.0
gfx.crash-guard.d3d11layers.appVersion: 48.0
gfx.crash-guard.d3d11layers.deviceID: 0x0e22
gfx.crash-guard.d3d11layers.driverVersion: 10.18.13.6839
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.status.: 2
gfx.crash-guard.status.d3d11layers: 2
media.gmp-eme-adobe.abi: x86_64-msvc-x64
media.gmp-eme-adobe.lastUpdate: 1470321419
media.gmp-eme-adobe.version: 17
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1471458931
media.gmp-gmpopenh264.version: 1.6
media.gmp-manager.buildID: 20160726073904
media.gmp-manager.lastCheck: 1471580908
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1470321428
media.gmp-widevinecdm.version: 1.4.8.866
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
network.cookie.prefsMigrated: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1471459215
places.history.expiration.transient_current_max_pages: 104858
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1470323773
ui.osk.debug.keyboardDisplayReason: IKPOS: Touch screen not found.

## Important Locked Preferences

## JavaScript

Incremental GC: true

## Accessibility

Activated: false
Prevent Accessibility: 0

## Library Versions

NSPR
Expected minimum version: 4.12
Version in use: 4.12

NSS
Expected minimum version: 3.24 Basic ECC
Version in use: 3.24 Basic ECC

NSSSMIME
Expected minimum version: 3.24 Basic ECC
Version in use: 3.24 Basic ECC

NSSSSL
Expected minimum version: 3.24 Basic ECC
Version in use: 3.24 Basic ECC

NSSUTIL
Expected minimum version: 3.24
Version in use: 3.24

## Experimental Features

**Comment by calzoneman** [comment] 2016-08-19 04:51
There was a miscommunication and the guide was written to recommend Greasemonkey, but it appears the script doesn't work with that (yet).  Until greasemonkey compatibility can be fixed, you can install [tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) instead and it will work on Firefox.

**Comment by Xaekai** [comment] 2016-08-19 04:55
If you're not a preexisting Greasemonkey user, you could try uninstalling it and installing Tampermonkey for FF.

Honestly I didn't even know Tampermonkey was available for Firefox till just a little bit ago or I wouldn't have even mentioned it in the wiki article. I've been a Chromium user for quite a while now and back when I used Firefox Greasemonkey was _the_ userscript host to use. It was my mistake for assuming that was still the case and that cal would have been testing with that extension. I will update the guide.

I am interested in why it won't work though. Maybe Greasemonkey has gone to shit in the interim?

**Comment by Jan02** [comment] 2016-08-19 04:56
greasemonkey has more than 1 million users, I think if there was an issue it would've gotten fixed by now

**Comment by calzoneman** [comment] 2016-08-19 04:57
No one is claiming Greasemonkey is wrong, just that it's currently incompatible with the script and we should investigate why.

**Comment by Jan02** [comment] 2016-08-19 04:58
from tampermonkey ff addon page:

> Please note that Firefox's WebExtension API is currently in an alpha state. This means Tampermonkey has (besides it's own bugs ;) still some issues caused by faulty or non-existent APIs.

**Comment by calzoneman** [comment] 2016-08-19 05:00
The fact of the matter is, this userscript works with Tampermonkey on Firefox (I tested it), and does not work with Greasemonkey (I forgot to test this before releasing it).  It doesn't matter whether who uses them or how new they are, that's simply the fact as it stands.

I plan to debug why it doesn't work in Greasemonkey as soon as I stop receiving GitHub notification emails complaining about said lack of compatibility.

**Comment by calzoneman** [comment] 2016-08-19 05:31
I've identified the problem and I think I have a solution, but I probably won't have it ready to release tonight.

**Comment by calzoneman** [comment] 2016-08-24 04:54
I guess you noticed by now that this is live on CyTube.  I also created the PR for making it work on other sites as well, will merge it soon: https://github.com/calzoneman/sync/pull/618

**Comment by calzoneman** [comment] 2016-08-25 02:15
Merged #618; closing this.

**Closed as completed by calzoneman** 2016-08-25 02:15 UTC
Labels: 3rd-party issue
