### ISSUE TITLE
Double changeMedia/setCurrent

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#203] opened 2013-07-07 11:53 UTC
Right now the server sends two sets of these frames when the video changes.

Also they are sent in the opposite order they were sent before. It used to be `changeMedia` then `setPosition`. Now it's `setCurrent` first followed by `changeMedia`.

**Comment by calzoneman** [comment] 2013-07-07 14:44
https://github.com/calzoneman/sync/blob/master/playlist.js#L438 is a duplicate of L436 of the same file.

**Closed as completed** 2013-07-07 14:50 UTC
Labels: bug
