### ISSUE TITLE
Google drive support 

### ISSUE THREAD

**Issue by ZenoNiQ** [calzoneman/sync#721] opened 2017-11-28 21:04 UTC
## Website Problem ##
https://beta.synchtube.me/r/Zone
https://drive.google.com/drive/u/1/my-drive
### Description of the Problem ###
Host: drive.google.com
File: .mkv 
Size: ~8GB
Chrome 64.0.3278.0, dev (64): all fine. ![chrome_2017-11-28_16-30-03](https://user-images.githubusercontent.com/1075196/33343489-2d96e5f0-d48e-11e7-9b41-f2712d1a4871.png)
Pale Moon Version: 27.6.1 (32-bit) (through Guerilla Scripting ): can't see script  ![palemoon_2017-11-28_22-49-50](https://user-images.githubusercontent.com/1075196/33343585-8554afac-d48e-11e7-827b-6a8abd61e99d.png)
Firefox (57.0 (64-bit)): Media coudn't be loaded
![firefox_2017-11-28_22-52-05](https://user-images.githubusercontent.com/1075196/33343651-d048c124-d48e-11e7-87be-0be0023b5182.png)

### System Information ###
  - Operating System Windows

Friends google chrome  can't even see script working same error msg as mine "Pale moon"
(Chrome OS win7 x64).

**Comment by calzoneman** [comment] 2017-11-29 01:42
>Pale Moon Version: 27.6.1 (32-bit) (through Guerilla Scripting ): can't see script

I'm not familiar with Guerilla Scripting.  It claims to be Greasemonkey compatible; your issue might be related to https://github.com/MoonchildProductions/Pale-Moon/issues/54 where Pale Moon apparently did not fully support the HTML5 addon API (`exportFunction` / `cloneInto`).  Opening the browser's JS console would probably reveal what's going on there with an error message.

> Firefox (57.0 (64-bit)): Media coudn't be loaded

This is usually caused by 3rd party cookies: https://github.com/calzoneman/sync/wiki/Google-Drive-Userscript-Installation-Guide#third-party-cookies

>Friends google chrome can't even see script working same error msg as mine "Pale moon"
(Chrome OS win7 x64).

There was a recent issue affecting older versions of Chrome which has since been fixed.  Please have them remove the userscript from Tampermonkey and then install it again.

**Comment by calzoneman** [comment] 2017-11-29 01:44
For Firefox 57, they completely redesigned the options menu so that screenshot probably doesn't match anymore.  But if you search "Cookies" in the preferences you should be able to find the option.

**Comment by Xaekai** [comment] 2017-11-29 02:11
I recognize those blue blurs. That's Sunshine of The Spotless Mind.

**Comment by calzoneman** [comment] 2017-11-30 04:32
I checked out Palemoon/Guerilla Script locally.

It doesn't appear to have an auto-installer, so I copied and pasted the script into its editor and got this error:

```
/*
Exception: ReferenceError: unsafeWindow is not defined
@Scratchpad/1:242:5
*/
```

~~It looks like it's not fully Greasemonkey compatible.~~

~~With a small workaround, I was able to get it working, so provided I can integrate that without breaking other browsers it should be feasible to support.~~

UPDATE: seems to be working for me, see below.

**Comment by calzoneman** [comment] 2017-11-30 04:42
Ignore the above, I discovered that it only affected the script editing sandbox, but the script worked as-is on the website itself.

In that case, I would need to see which specific errors you're getting in the console in order to know what's going on.  I'm planning to add some better debug reporting to the script.

![2017-11-29-204128_1917x1058_scrot](https://user-images.githubusercontent.com/385672/33413315-bfcdcc74-d545-11e7-85a7-5c5c144bd213.png)

**Comment by ZenoNiQ** [comment] 2017-11-30 15:27
Firefox fxd by cookies from "3rd part"
Pale Moon by update script to 1.6 ![palemoon_2017-11-30_17-22-37](https://user-images.githubusercontent.com/1075196/33438324-25c3adca-d5f3-11e7-8512-2359f49afc74.png)
Friend Chrome dev build  last version (i reinstall in myself) don't tested yet.

**Comment by calzoneman** [comment] 2017-12-01 04:07
I'm going to go ahead and close this since you got your Firefox and Pale Moon installations working.  Feel free to comment again if you have further issues -- self-service debugging guide and better errors coming soon.

**Closed as completed by calzoneman** 2017-12-01 04:07 UTC
Labels: question
