### ISSUE TITLE
YouTube does not respect quality preference

### ISSUE THREAD

**Issue by Bittenspoder** [calzoneman/sync#726] opened 2017-12-15 01:30 UTC
Please fill out the templates below to the best of your ability, based on whether your problem is with using the website or with running your own server.

## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [ ] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [*] Disabling all browser extensions
  - [*] Using a clean channel with no customizations
  
### Description of the Problem ###

  - What triggers the problem? inaction of switching 240-1080/highest setting for youtube in NavBar -> OPTIONS -> Playback Tab -> Quality Preference
  - What happens? video refreshes quality unchanged
  - What do you expect to happen instead? quality of video to change when refreshed

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** windows
  - **Web Browser (Firefox / Chrome / Other):** Chrome
  - **Error Messages Displayed:** none
  - **Screenshot of JavaScript Console:**  https://gyazo.com/4689aa539a41563d7cd290304e131cfa < with extensions
https://gyazo.com/9aaa50a10c0370354d473acb27808040 w/o
 changed selection of quality then refreshed player for console
  
_On Firefox, press `Ctrl+Shift+K` to open the JavaScript console.  On Chrome, press `Ctrl+Shift+J`._

**Comment by calzoneman** [comment] 2017-12-15 07:04
~~Hi,~~

~~I tested with my example 1080p drive video and confirmed that both the gear icon on the video player itself and the Options->Playback quality preference are working as expected in Firefox and Chromium.~~

~~1. Can you provide an example link to a video that you're having a problem with?  Some videos, especially if you just uploaded them, may not have all qualities generated by Google Drive yet.~~
~~2. Your console screenshot shows some additional output which indicates that a custom script is running on the channel.  Please try disabling *all* custom scripts from the Options menu and see if you're still having the issue, in case your channel JS might be patching the player.~~

Issue appears to be related to YouTube, not Drive.

**Comment by calzoneman** [comment] 2017-12-15 07:04
Actually can you clarify something?  The title of the issue confuses me, are you saying it *works* with YouTube and *doesn't* work for drive, or that it *works* for drive and *doesn't* work for YouTube?

**Comment by calzoneman** [comment] 2017-12-15 07:13
I went ahead and checked YouTube and it does appear to be a regression.  The YouTube player API `setPlaybackQuality()` does absolutely nothing.

I see a few references to this on the issue tracker, such as [1] and [2], which have deleted comments but appear to suggest that something changed in YouTube's API about the way these are handled.  In particular, it may no longer be possible to change the quality once the video has started playing, which is kind of stupid in my opinion, but since CyTube only explicitly sets the quality at the beginning it may be possible to work around this.

[1]: https://issuetracker.google.com/issues/35174491
[2]: https://issuetracker.google.com/issues/35172976

**Comment by calzoneman** [comment] 2017-12-15 07:19
Those above tickets are pretty stale, but there was a new one created December 9 and not commented yet: https://issuetracker.google.com/issues/70440398

From what I can tell, the `setPlaybackQuality` API doesn't work at all at the moment which means there's no way to control the quality preference of the YouTube player.

**Comment by calzoneman** [comment] 2017-12-15 07:36
I could not figure out how to add a comment to that bug report, so I filed a new bug report with YouTube: https://issuetracker.google.com/issues/70699731

Hopefully they reply to that and fix it, but if not, I'm afraid there's not anything else I can do here.

**Comment by Xaekai** [comment] 2017-12-16 05:11
We meet once again Google's fault label. heh

**Comment by calzoneman** [comment] 2018-02-28 00:50
It appears Google does not intend to support this anymore:

>Status: Won't Fix (Intended Behavior)
>An update -- due to changes in our player infrastructure, the player will no longer honor requests to set a manual playback quality via the API. As documented, the player has always made a "best effort" to respect the requested quality.
>
>The documentation will be updated in the future to indicate this call is no longer supported, though it will still be available as a "no-op" for compatibility purposes.

So I guess the only thing left to do here is update CyTube to add a disclaimer that quality selection is unsupported for YouTube.

**Comment by calzoneman** [comment] 2018-03-06 06:22
Closing this out via the above commit.  Will be in the next live update.

**Closed as completed by calzoneman** 2018-03-06 06:22 UTC
Labels: bug, Google's fault
